### ISSUE TITLE
Document the required AAD Apps that require Kusto viewer permissions

### ISSUE THREAD

**Issue by smith1511** [Azure/adx-mon#225]
It would be good to document the various ADX-Mon AAD Apps that require Kusto viewer permissions.

This is what I've captured from a couple of threads.

public cloud prod adx-mon app:
appID: c6a42369-7f08-4faf-a52f-d9c2f26863b3
tenantID: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

public cloud prod deployment app used for CI:
appID: 785a3a96-8b24-4f18-8c50-f94400533fbd
tenantID: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

publicintv2
appID: c8b9fc64-fc6a-471b-9a96-dae355f5fe2e
tenantID: 33e01921-4d64-4f8c-a055-5bdaffd5e33d

corpdev: 1e14d0ca-5439-4345-85c9-4bd1459294e5
tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
 
corptest: c0d69910-3ed9-4abd-8d5b-c186731c2dde
tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by mkeesey** [comment]
This is specific to our deployment of this project internally and not to the OSS project.
